Fix artifact name in project_dependencies action
eProsima/DDS-Pipe pull request #123
Opened 2024-07-17 14:05 UTC by irenebm

2024-07-17 14:30 UTC, Tempate requested changes
Thanks for taking the time to update the artifacts. It may be a hustle but it needs to be done.

2024-07-17 14:30 UTC, Tempate commented on .github/workflows/reusable-workflow.yml
Please update the `PLATFORM_SUPPORT.md`.

2024-07-17 14:30 UTC, Tempate commented on .github/workflows/reusable-workflow.yml
There was also a temporary, ugly workaround on `TopicQoS` for Ubuntu 20.04. Try to get rid of it and see if it works in Ubuntu 22 & 24.

2024-07-18 05:54 UTC, Tempate approved these changes
LGTM

2024-07-18 06:21 UTC, rsanchez15 approved these changes

2024-07-18 06:21 UTC, merged