Add custom forwarding routes feature
eProsima/DDS-Pipe pull request #56
Opened 2023-08-01 07:33 UTC by juanlofer-eprosima

2023-09-04 09:11 UTC, Tempate requested changes

2023-09-25 06:41 UTC, juanlofer-eprosima commented on ddspipe_yaml/src/cpp/YamlReader_features.cpp
> +        const YamlReaderVersion version)
There is no performance gain for enums, just like it is the case for booleans for example.

2023-09-25 06:44 UTC, juanlofer-eprosima commented on ddspipe_core/include/ddspipe_core/configuration/RoutesConfiguration.hpp
> +    DDSPIPE_CORE_DllAPI virtual bool is_valid(
As far as I know, virtual and override keywords are optional in overriding classes. So no, but it does not hurt to have it.

2023-09-25 06:44 UTC, juanlofer-eprosima commented on ddspipe_core/include/ddspipe_core/configuration/TopicRoutesConfiguration.hpp
> +    DDSPIPE_CORE_DllAPI virtual bool is_valid(
Same answer as before.

2023-09-25 06:45 UTC, juanlofer-eprosima commented on ddspipe_core/src/cpp/communication/dds/DdsBridge.cpp
> +            std::map<ParticipantId, std::shared_ptr<IWriter>> writers_except_one =
Is it?

2023-09-25 07:27 UTC, juanlofer-eprosima commented on ddspipe_core/src/cpp/communication/dds/DdsBridge.cpp
> +            std::map<ParticipantId, std::shared_ptr<IWriter>> writers_except_one =
And incompatible with merging if-else statements into one suggestion.

2023-09-26 06:10 UTC, Tempate requested changes

2023-09-26 06:10 UTC, Tempate commented on ddspipe_yaml/include/ddspipe_yaml/yaml_configuration_tags.hpp
> +constexpr const char* ROUTES_SRC_TAG("src"); //! Route source
I would write "Route's source participant" and "Route's destination participants"

2023-09-26 06:10 UTC, Tempate commented on ddspipe_core/src/cpp/core/DdsPipe.cpp
> +        RoutesConfiguration routes_config = topic_routes_config_().count(topic) !=
I think it would be more readable if the one-liner if statement was replaced by a normal if statement.

2023-09-26 07:30 UTC, Tempate approved these changes
LGTM

2023-09-26 07:30 UTC, merged