Reset cache change que return to pool
eProsima/DDS-Pipe pull request #9
Opened 2023-02-23 10:12 UTC by jparisu

2024-05-30 10:51 UTC, Tempate commented
After many long hours, we have been able to come up with a scenario that, without this fix, keeps throwing:
```
[RTPS_WRITER Error] Error sending fragment (21, 2) -> Function deliver_sample_nts
[RTPS_WRITER Error] Cannot add DATA_FRAG submsg to the CDRMessage. Buffer too small -> Function add_data_frag
```
until it SEGFAULTs. This feature fixes it, stopping the errors and the SEGFAULT.

2024-05-30 10:56 UTC, Tempate commented
After many long hours, we have been able to come up with a scenario that, without this fix, keeps throwing:
```
[RTPS_WRITER Error] Error sending fragment (21, 2) -> Function deliver_sample_nts
[RTPS_WRITER Error] Cannot add DATA_FRAG submsg to the CDRMessage. Buffer too small -> Function add_data_frag
```
until it SEGFAULTs. This feature fixes it, stopping the errors and the SEGFAULT.

2024-06-04 07:52 UTC, LuciaEchevarria99 requested changes

2024-06-04 07:52 UTC, LuciaEchevarria99 commented on ddspipe_participants/include/ddspipe_participants/efficiency/cache_change/CacheChangePool.hpp
Insert CacheChange header (CacheChange.h) and sort alphabetically the cpp_utils includes

2024-06-05 07:58 UTC, LuciaEchevarria99 approved these changes
LGTM

2024-06-05 10:02 UTC, merged