[19983] Publish Fast-DDS's Logs
eProsima/DDS-Pipe pull request #92
Opened 2024-02-15 14:32 UTC by Tempate

In this version, users can configure through the YAML the publication of Fast DDS's logs. 

Merge after:
- https://github.com/eProsima/DDS-Pipe/pull/86

2024-02-26 11:05 UTC, LuciaEchevarria99 requested changes

2024-02-26 11:05 UTC, LuciaEchevarria99 commented on ddspipe_core/include/ddspipe_core/configuration/DdsPipeLogConfiguration.hpp
> +    bool stdout_enable = false;
If we don't change stdout in YAML but set --log-verbosity info in the command-line, will the logs still not be displayed? This implies that if you wish to configure them via the command-line, you'll also need to set stdout=true in YAML. I notice a slight inconsistency in having to configure them in both places. Perhaps this variable could default to true if the log and/or filter are configured via the command-line?

2024-02-26 11:05 UTC, LuciaEchevarria99 commented on ddspipe_yaml/test/unittest/yaml_reader/log_configuration/YamlReaderLogConfiguration.cpp
Add a test with the case:
            R"(
            stdout: false
            verbosity: info
        )"
and check if logs are displayed

2024-02-28 14:07 UTC, Tempate commented on ddspipe_core/src/cpp/logging/DdsLogConsumer.cpp
> +    if (!accept_entry_(entry))
https://medium.com/swlh/return-early-pattern-3d18a41bba8

2024-02-29 07:44 UTC, LuciaEchevarria99 requested changes

2024-02-29 07:44 UTC, LuciaEchevarria99 commented on ddspipe_core/include/ddspipe_core/logging/DdsLogConsumer.hpp
> + * Registering this consumer in Fast DDS's Log publishes the log entries accepted by the BaseLogConsumer.
Is this sentence completely accurate?

2024-03-04 07:01 UTC, LuciaEchevarria99 requested changes

2024-03-04 13:37 UTC, Tempate commented on ddspipe_core/include/ddspipe_core/logging/DdsLogConsumer.hpp
> + * Registering this consumer in Fast DDS's Log publishes the log entries accepted by the BaseLogConsumer.
Yes, why do you think it isn't?

2024-03-04 13:39 UTC, Tempate commented on ddspipe_core/CMakeLists.txt
I will rebase once it's fully approved and merged.

2024-03-06 15:10 UTC, merged